### ISSUE TITLE
How was the loss sigma in the paper achieved?

### ISSUE THREAD

**Issue by Kimiraha** [EliasNehme/NPPC#1]
Thank you for your wonderful work and open source code.
Regarding the NPPC model training process, how is the loss sigma implemented?
I observed that reconst_err implements the loss w in the base step of NPPC trainer and second_moment_mse seems to be related to the loss sigma.
But why is w_norm used as sigma here?

**Comment by EliasNehme** [comment]
Hey, thanks for the kind words.
So as we mention in the paper, instead of outputting an additional set of $K$ scalars for $\sigma_1,\dots,\sigma_K$, we use the norms of the predicted PCs to encode this information. Note that by definition the PCs should be normalized to have a unit norm. So in the `reconst_err` loss (=PC loss) we use the normalized PCs `w_hat_mat` where $\boldsymbol{w}_i$ has a norm of 1, and in the `second_moment_mse` loss (=sigma loss) we use the norms of the PCs before normalization `w_norms` as our way of encoding $\sigma_1,\dots,\sigma_K$.

**Comment by Kimiraha** [comment]
> Hey, thanks for the kind words. So as we mention in the paper, instead of outputting an additional set of K scalars for σ1,…,σK, we use the norms of the predicted PCs to encode this information. Note that by definition the PCs should be normalized to have a unit norm. So in the `reconst_err` loss (=PC loss) we use the normalized PCs `w_hat_mat` where wi has a norm of 1, and in the `second_moment_mse` loss (=sigma loss) we use the norms of the PCs before normalization `w_norms` as our way of encoding σ1,…,σK.

Thank you for your reply.
Based on your explanation, I noticed that the output after orthogonalisation is the principal component vector without normalisation, which solved my problem.
Thanks again for your explanation!
